name = "gdrive-copier"
compatibility_date = "2024-12-01"
pages_build_output_dir = ".vercel/output/static"

# Environment variables (these will need to be set in Cloudflare dashboard)
[vars]
NODE_ENV = "production"

# D1 Database binding
[[d1_databases]]
binding = "DB"
database_name = "gdrive-copier-db"
database_id = "your-database-id-here"

# KV namespace for sessions (optional)
[[kv_namespaces]]
binding = "SESSIONS"
id = "your-kv-namespace-id-here"